 /***************************************************************/
/***          Automatically generated support file             ***/
 /***************************************************************/

 /* This file is automatically generated by 'files.py'.
    DO NOT MODIFY. Changes will be overwritten ! */


 /* Do not use this file directly. Only included from psyco.c. */

#if ALL_STATIC
# include "processor.c"
# include "dispatcher.c"
# include "vcompiler.c"
# include "codemanager.c"
# include "mergepoints.c"
# include "pycencoding.c"
# include "selective.c"
# include "linuxmemchk.c"
# include "Python/pycompiler.c"
# include "Python/pbltinmodule.c"
# include "Objects/pobject.c"
# include "Objects/pabstract.c"
# include "Objects/pclassobject.c"
# include "Objects/pdescrobject.c"
# include "Objects/pdictobject.c"
# include "Objects/pfloatobject.c"
# include "Objects/pfuncobject.c"
# include "Objects/pintobject.c"
# include "Objects/piterobject.c"
# include "Objects/plistobject.c"
# include "Objects/plongobject.c"
# include "Objects/pmethodobject.c"
# include "Objects/pstringobject.c"
# include "Objects/pstructmember.c"
# include "Objects/psycofuncobject.c"
# include "Objects/ptupleobject.c"
# include "Modules/parray.c"
#else /* if !ALL_STATIC */
  EXTERNFN void psyco_processor_init(void);	/* processor.c */
  EXTERNFN void psyco_compiler_init(void);	/* vcompiler.c */
  EXTERNFN void psyco_pycompiler_init(void);	/* Python/pycompiler.c */
  EXTERNFN void psyco_bltinmodule_init(void);	/* Python/pbltinmodule.c */
  EXTERNFN void psy_object_init(void);	/* Objects/pobject.c */
  EXTERNFN void psy_classobject_init(void);	/* Objects/pclassobject.c */
  EXTERNFN void psy_descrobject_init(void);	/* Objects/pdescrobject.c */
  EXTERNFN void psy_dictobject_init(void);	/* Objects/pdictobject.c */
  EXTERNFN void psy_floatobject_init(void);	/* Objects/pfloatobject.c */
  EXTERNFN void psy_funcobject_init(void);	/* Objects/pfuncobject.c */
  EXTERNFN void psy_intobject_init(void);	/* Objects/pintobject.c */
  EXTERNFN void psy_iterobject_init(void);	/* Objects/piterobject.c */
  EXTERNFN void psy_listobject_init(void);	/* Objects/plistobject.c */
  EXTERNFN void psy_longobject_init(void);	/* Objects/plongobject.c */
  EXTERNFN void psy_methodobject_init(void);	/* Objects/pmethodobject.c */
  EXTERNFN void psy_stringobject_init(void);	/* Objects/pstringobject.c */
  EXTERNFN void psy_psycofuncobject_init(void);	/* Objects/psycofuncobject.c */
  EXTERNFN void psy_tupleobject_init(void);	/* Objects/ptupleobject.c */
  EXTERNFN void psyco_initarray(void);	/* Modules/parray.c */
#endif /* !ALL_STATIC */

inline void initialize_all_files(void) {
  psyco_processor_init();	/* processor.c */
  psyco_compiler_init();	/* vcompiler.c */
  psyco_pycompiler_init();	/* Python/pycompiler.c */
  psyco_bltinmodule_init();	/* Python/pbltinmodule.c */
  psy_object_init();	/* Objects/pobject.c */
  psy_classobject_init();	/* Objects/pclassobject.c */
  psy_descrobject_init();	/* Objects/pdescrobject.c */
  psy_dictobject_init();	/* Objects/pdictobject.c */
  psy_floatobject_init();	/* Objects/pfloatobject.c */
  psy_funcobject_init();	/* Objects/pfuncobject.c */
  psy_intobject_init();	/* Objects/pintobject.c */
  psy_iterobject_init();	/* Objects/piterobject.c */
  psy_listobject_init();	/* Objects/plistobject.c */
  psy_longobject_init();	/* Objects/plongobject.c */
  psy_methodobject_init();	/* Objects/pmethodobject.c */
  psy_stringobject_init();	/* Objects/pstringobject.c */
  psy_psycofuncobject_init();	/* Objects/psycofuncobject.c */
  psy_tupleobject_init();	/* Objects/ptupleobject.c */
  psyco_initarray();	/* Modules/parray.c */
}
