 /***************************************************************/
/***          Automatically generated support file             ***/
 /***************************************************************/

 /* This file is automatically generated by 'files.py'.
    DO NOT MODIFY. Changes will be overwritten ! */


  /* internal part for psyco.c */
#if ALL_STATIC
#else /* if !ALL_STATIC */
#endif /* !ALL_STATIC */

inline void initialize_processor_files(void) {
}
