#!/usr/bin/env python
from __future__ import print_function
import sys

def gen_blocks():
    for line in open('codegen.log'):
        if 'BEGIN_CODE' in line:
            begin = line.split()[-1]
        elif 'END_CODE' in line:
            yield begin, line.split()[-1]
            del begin

def hex_to_int(h):
    return int(h, 16)

ARG = hex_to_int(sys.argv[1])
for begin, end in gen_blocks():
    if hex_to_int(begin) <= ARG < hex_to_int(end):
        print(begin, end)

        
