#!/usr/bin/env python
from __future__ import print_function
import sys
from tools import *


if __name__ == "__main__":
    ARG = hex_to_int(sys.argv[1])
    for begin, end in gen_blocks():
        if hex_to_int(begin) <= ARG < hex_to_int(end):
            print(begin, end)

        
