#! /usr/bin/env python
from __future__ import print_function

import glob
import test as python_tests
import os
import subprocess

def main():
    test_src_dir = os.path.split(python_tests.__file__)[0]
    tests = list(sorted(glob.glob(os.path.join(test_src_dir, 'test_*.py'))))
    for test in tests:
        print("Test:", test)
        returncode = subprocess.call(['ni', test])
        print("Return Code:", returncode)

if __name__ == "__main__":
    main()
