#!/usr/bin/env python

import sys
import pointbreak
import nianalyser


class Counter:
    def __init__(self):
        self.eval_frame_count = 0
        self.ni_run_count = 0

    def eval_frame(self, db):
        self.eval_frame_count += 1
        return True

    def run(self, db):
        self.ni_run_count += 1
        return True


cmd = sys.argv[1] + ' ' + ' '.join(["'%s'" % (i,) for i in sys.argv[2:]])
db = pointbreak.create_debugger(cmd)
counter = Counter()
db.add_breakpoint('NiEval_EvalFrame', counter.eval_frame)
db.add_breakpoint('NiCode_Run', counter.run)
db.continue_to_last_event()

print(counter.eval_frame_count, counter.ni_run_count)

