#!/usr/bin/env python
from __future__ import print_function
import subprocess
from distutils.sysconfig import get_python_inc

def compare(c_code, asm_code):
    asm_out = subprocess.check_output("./asm '%s' | grep 0: | cut -f 2" % (asm_code,), shell=True).strip()
    c_out = subprocess.check_output("gcc -I%s test_mcg_template.c -DREPLACE_ME='%s' && ./a.out && rm a.out" % (get_python_inc(), c_code,), shell=True).strip()
    if asm_out != c_out:
        print(c_code, '!=', asm_code)
        print(c_out, '!=', asm_out)
        print()

for l in open('asm_test_cases.txt'):
    if l.strip() and ';' in l:
        compare(*l.strip().split(';'))
