#!/usr/bin/env python
from __future__ import print_function
import sys
from tools import *

blocks = list(gen_blocks())
start, finish = None, None
for line in open('trace_execution.log'):
    pc = line.split()[0].split(':')[1]
    for begin, end in blocks:
        if hex_to_int(begin) <= hex_to_int(pc) < hex_to_int(end):
            break
    else:
        raise Exception('No match for %s' % (pc,))
    if finish == None:
        start, finish = begin, end
    elif finish != begin:
        print(start, finish)
        start, finish = begin, end
    else:
        finish = end
if finish != None:
    print(start, finish)



        
